services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quant_backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: quant_frontend
    working_dir: /app/frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    command: ["streamlit", "run", "dashboard.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
