# Use the official PostgreSQL image
FROM postgres:latest

# Set environment variables for default database setup
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=portfolio_db

# Expose PostgreSQL port
EXPOSE 5432
